### ISSUE TITLE
Add some more separation to challenge bars between different challenges

### ISSUE THREAD

**Issue by DavidFerrerBeltran** [jlweston/ngu-save-analyser#28]

**Comment by jlweston** [comment]
Hi David,

Do you mean between the different difficulties for a given challenge, or some more padding between different challenges? 

I'm looking to tweak the visuals a bit soon, so I appreciate your input.

Jamie

**Comment by DavidFerrerBeltran** [comment]
Padding between challenges

**Comment by jlweston** [comment]
I've embraced Bootstrap tables, and they've added a bit more room between challenges 👌
