### ISSUE TITLE
Save/Load string/URL

### ISSUE THREAD

**Issue by Sancdar** [jlweston/ngu-save-analyser#31]
It would be nice to be able to share an analysis of a save file or compare between save files without resorting to screenshots or passing actual save files around.

**Comment by jlweston** [comment]
I was actually thinking how I might do this but I need to find a way to keep the costs down. At the moment, the site's a static page with all the work done in the browser - introducing a sharing feature would likely mean the addition of some kind of database and an API to save/load files from the DB.

**Comment by Sancdar** [comment]
That's why I was thinking a save string would work, because you could have the user carrying the data for you and you'd just need to encode/decode plaintext analysis results in base64 or something. Everything could still be done in browser, right?

**Comment by jlweston** [comment]
Given the amount of data that would need to be shared, I can imagine the save string being quite long. As people will likely be sharing their saves in chatrooms, I'm conscious that the strings themselves should be pretty short. This is why I'm leaning toward a DB approach with a short URL to retrieve a save.

I'm back from vacation now, so I'll be spending some more time on this project over the next few days. I'd like to prioritise this issue, as I can imagine it driving higher usage of the tool, which in turn should drive more feedback.
