### ISSUE TITLE
Hook into Gear Optimizer

### ISSUE THREAD

**Issue by yono38** [jlweston/ngu-save-analyser#37]
I'm not sure specifically how this would work, but essentially we'd use the savefile data to determine the user's current inventory (existing items + their levels) to create some kind of export data that could be used for the gear optimizer, so it would optimize based on the user's available items

The way that the savefile stores items is by the `id` property, which matches the ID in the in-game Item List, and has another property called `level` with the item's current level. It uses `id 0` when the slot is empty. 

We'd need to merge these keys in PlayerData `inventory`:
`["spaces","item1","item2","head","chest","legs","boots","weapon","weapon2","items","accs"]`

Create an array of item objects: `[{id: <ITEM_LIST_ID>, level: <ITEM_LEVEL>}]`

**Comment by rvazarkar** [comment]
Just FYI I helped add this into GO already, so the functionality is there
