### ISSUE TITLE
Expose API for reading save file to JSON

### ISSUE THREAD

**Issue by rvazarkar** [jlweston/ngu-save-analyser#40]
Is there any chance you would consider exposing an API endpoint to submit a save file and return the shared json back? Would be nice to be able to directly use a save file from GO by calling the API endpoint and requesting the JSON.

**Comment by jlweston** [comment]
The entire app runs in the browser, with the exception of temporarily storing the JSON on the server side when you use the sharing functionality. This was done for cost reasons and I have no plans to implement any data processing on the server side.

You're welcome to re-use the code that parses the save file and create your own implementation but I won't be adding features to ngusav.es that increase the running costs. I've kept it ad-free and don't ask for donations but can only do this if I keep the costs low.
